spring.datasource.url=jdbc:mysql://localhost:3306/guespy
spring.datasource.username=guespy_user
spring.datasource.password=Ryuk2002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true 
# Prints SQL queries in the console 

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Tells Hibernate which SQL flavor to use
