package com.game.gueSpy.enums;


public enum GameStatus {
    NOT_STARTED,
    CATEGORY_SELECTION,
    GROUP_SELECTION,
    GAME_OPTION_SELECTION,
    WORD_AND_SPY_REVEAL,
    DISCUSSION_TIME,
    SCORING
}
/* 
ALTER TABLE user_game_details
MODIFY COLUMN game_status 
ENUM('NOT_STARTED', 'CATEGORY_SELECTION', 'GROUP_SELECTION', 'GAME_OPTION_SELECTION', 'WORD_AND_SPY_REVEAL', 'DISCUSSION_TIME', 'SCORING');
*/

